### ISSUE TITLE
Using some of your code in a derivative project

### ISSUE THREAD

**Issue by chrissnell** [pr8kerl/f5er#1]
Hi Ian,

I would like to use some of your code--specifically, the request and response structs--in a derivative project that I'm working on.  Per your license, this is okay if I keep your copyright intact and maintain a free license.  Are you okay with this if my project is licensed under the MIT license?  

I plan on implementing the REST calls myself but copying your structs would save a massive amount of time.   Thanks for producing f5er!

Chris

**Comment by pr8kerl** [comment]
Hey Chris,

Feel free. Glad it's useful. Yep - those structs are a pain - too many options. Thanks for checking in.

Cheers,

Ian
