### ISSUE TITLE
401 Unauthorized Error: "Message": "loginProviderName is invalid."

### ISSUE THREAD

**Issue by BoxingOctopus** [pr8kerl/f5er#18]
Got the following error when trying to log in:

```
{
	"Url": "https://[redacted]/mgmt/shared/authn/login",
	"Method": "POST",
	"Params": {},
	"Payload": {
		"loginProviderName": "tmos",
		"password": "[redacted]",
		"username": "[redacted]"
	},
	"RawPayload": false,
	"Result": {
		"token": {
			"token": "",
			"expirationMicros": 0
		}
	},
	"CaptureResponseBody": false,
	"ResponseBody": null,
	"Error": {
		"Message": "loginProviderName is invalid.",
		"Errors": null
	},
	"Userinfo": null,
	"Header": null,
	"Transport": null
}
2017/07/17 15:05:07 --------------------------------------------------------------------------------
2017/07/17 15:05:07 REQUEST
2017/07/17 15:05:07 --------------------------------------------------------------------------------
2017/07/17 15:05:07 Method: GET
2017/07/17 15:05:07 URL: https://[redacted]/mgmt/tm/ltm/virtual
2017/07/17 15:05:07 Header: map[X-F5-Auth-Token:[] Accept:[application/json]]
2017/07/17 15:05:07 Form: map[]
2017/07/17 15:05:07 Payload:
2017/07/17 15:05:07 null
2017/07/17 15:05:07 --------------------------------------------------------------------------------
2017/07/17 15:05:07 RESPONSE
2017/07/17 15:05:07 --------------------------------------------------------------------------------
2017/07/17 15:05:07 Status:  401
2017/07/17 15:05:07 Header:
2017/07/17 15:05:07 {
	"Cache-Control": [
		"no-store, no-cache, must-revalidate"
	],
	"Content-Length": [
		"1515"
	],
	"Content-Security-Policy": [
		"default-src 'self'  'unsafe-inline' 'unsafe-eval'"
	],
	"Content-Type": [
		"application/json"
	],
	"Date": [
		"17 Jul 2017 19:04:55 UTC"
	],
	"Expires": [
		"-1"
	],
	"Pragma": [
		"no-cache"
	],
	"Server": [
		"com.f5.rest.common.RestRequestSender"
	],
	"Strict-Transport-Security": [
		"max-age=16070400; includeSubDomains"
	],
	"X-Content-Type-Options": [
		"nosniff"
	],
	"X-Frame-Options": [
		"SAMEORIGIN"
	],
	"X-Xss-Protection": [
		"1; mode=block"
	]
}
2017/07/17 15:05:07 Body:
2017/07/17 15:05:07 {
	"code": 401,
	"message": "X-F5-Auth-Token does not exist.",
	"referer": "[redacted]",
	"restOperationId": 18365773,
	"errorStack": [
		"java.lang.SecurityException: X-F5-Auth-Token does not exist.",
		"at com.f5.rest.workers.ForwarderWorker.failPermissionValidation(ForwarderWorker.java:686)",
		"at com.f5.rest.workers.ForwarderWorker.evaluatePermission(ForwarderWorker.java:629)",
		"at com.f5.rest.workers.ForwarderPassThroughWorker.onForward(ForwarderPassThroughWorker.java:211)",
		"at com.f5.rest.workers.ForwarderPassThroughWorker.onGet(ForwarderPassThroughWorker.java:418)",
		"at com.f5.rest.common.RestWorker.callDerivedRestMethod(RestWorker.java:1042)",
		"at com.f5.rest.common.RestWorker.callRestMethodHandler(RestWorker.java:1009)",
		"at com.f5.rest.common.RestServer.processQueuedRequests(RestServer.java:1002)",
		"at com.f5.rest.common.RestServer.access$000(RestServer.java:45)",
		"at com.f5.rest.common.RestServer$1.run(RestServer.java:248)",
		"at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)",
		"at java.util.concurrent.FutureTask.run(FutureTask.java:262)",
		"at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)",
		"at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)",
		"at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)",
		"at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)",
		"at java.lang.Thread.run(Thread.java:744)\n"
	]
}
{
	"Status": 401,
	"Message": "X-F5-Auth-Token does not exist."
}
2017/07/17 15:05:07 error: 401 Unauthorised - check your username and passwd
```

**Comment by pr8kerl** [comment]
What version of Big-IP are you running??
What is the cmd you are trying to run (looks like f5er show virtual )?
Does it work if you use the admin user credentials?

**Comment by BoxingOctopus** [comment]
```
Sys::Version
Main Package
  Product  BIG-IP
  Version  11.5.4
  Build    2.0.291
  Edition  Hotfix HF2
  Date     Thu Jul 21 16:10:24 PDT 2016
```

Also, yes, this was an admin user attempting to execute the command, and yes, I was using `f5er show virtual`.

**Comment by pr8kerl** [comment]
Mmmmm.
Does this command work ok (change the password and device hostname of course) ??
```
curl -sk -u admin:password -H "Content-Type: application/json" https://x.x.x.x/mgmt/tm/sys/folder
```
If so, basic auth works ok via REST. Then I'm suspecting some sort of issue with the use of token auth on this version, or device config.
I build and test against v11.6 and others have tested using v12 ok.

Does your device use local authentication? I guess at least is the admin user a locally defined user, or are all users in LDAP or some other source?? This tmos module means the user it is trying to use is defined locally on the device.

You could try this [python module]( https://github.com/F5Networks/f5-icontrol-rest-python) to test it isn't the go code.

If this python code works after installing the f5 module, then it's my code's issue. This snippet is using token auth too.

```
#/usr/bin/env python
from icontrol.session import iControlRESTSession
icr_session = iControlRESTSession('admin', 'admin password', token=True)

resp = icr_session.get(
'https://x.x.x.x/mgmt/tm/ltm/virtual',
name='virtual server name',
partition='Partition name'
)

print resp
print resp.content
```
But if you get a 401 from the python one. Then it's an issue with your device/user setup.

Let me know.

**Comment by BoxingOctopus** [comment]
Hey, yeah I got a 401 with the curl command.

**Comment by BoxingOctopus** [comment]
Scratch that, I just tried with another user and was able to authenticate via curl, but not via f5er.

**Comment by bestes** [comment]
I'm having the same (or similar) issue. I have a set of BIG-IP 4000's and use f5er to get the configs. It was working with all of them, then suddenly stopped working on most. My test command is "./f5er show device", which returns a 401 with the message "loginProviderName is invalid." on some of them and works on others. If I do essentially the same thing with curl, it works. I have a mix of 11.6.0 and 12.0.0.

**Comment by bestes** [comment]
I was able to workaround the issue with the following change in f5/f5.go:

// Removed loginProviderName
// It does not appear to be required and prevents login in some cases

LoginData := map[string]string{"username": f.Username, "password": f.Password}

was:

LoginData := map[string]string{"username": f.Username, "password": f.Password, "loginProviderName": "tmos"}

**Comment by pr8kerl** [comment]
@bestes Sweet. Thanks for the tip - really appreciated. I will do some reading. I only have version 11.6.0 to test against which is behind in some of this auth functionality. I'll have a play this weekend.

Cheers.

**Comment by pr8kerl** [comment]
@bestes I have added a new cli flag --token=(true|false) which can turn off the token authentication method (and use basic auth only). The default is to use token auth (which was the previous behaviour).

Can you give this one a try and make sure it works for me please?? It works fine in both modes on my 11.6 cluster.

If this is working - it still begs the question as to why the auth stopped for you against some devices??
Did you recently rebuild f5er? Or were any of your devices recently patched??
Was it a case that the auth worked against one version of Big-IP and failed against the other?

Anyway - any info gratefully received. Tx.

**Comment by bestes** [comment]
I'll give it a try and let you know. Sorry I didn't just make a patch the first time, but was unclear on the purpose of that user. As for the change, I need to review the diffs. I'm not sure what exactly to look for, but didn't see anything when I searched for tmos.

**Comment by pr8kerl** [comment]
@bestes No probs at all. Don't stress too much about trying to find what changed. Just if you are curious and have time.  I haven't hit this issue at all with my single 11.6 cluster so can't reproduce or test.
The LoginProviderName tmos bit just sets the big-ip to token auth mode instead of basic. I think I'll actually change the flag and make basic auth the default. It seems to perform better - token auth needs an extra request to grab the token before making the f5er request - which adds delay.
Will do that soon.
Cheers

**Comment by bestes** [comment]
Looks great! I tested on multiple 11.6.0 and 12.0.0 devices. It works if I use "export F5_TOKEN='true'" or not. No other changes were necessary. I'll bet it is faster, too, but haven't had time to test that yet. I did this test from commit 49b88a1e043e7f35a485570ab43389a58764cc6c  Thanks!

**Comment by pr8kerl** [comment]
Thanks @bestes I've started doing releases so you can grab the latest from [here](https://github.com/pr8kerl/f5er/releases/tag/v0.3.1) which now has basic auth as default. Other than that it's the same. If you ever want to do a PR - feel free. ;)

Thanks.

**Comment by pr8kerl** [comment]
Finally got there I think. I'm going to close this one. Reopen if any further auth issues.
