### ISSUE TITLE
Using system proxy from env

### ISSUE THREAD

**Issue by qiaolei81** [pr8kerl/f5er#22]
Sometimes we may need access the F5 through some proxies, shall we support the system proxy from environment variables?

**Comment by pr8kerl** [comment]
@qiaolei81 Sorry - I only just noticed this issue.

Sounds like a good idea.
I don't use/need a proxy but f5er may already actually support it as it is using the the standard http client package inside.

Have you tried using the HTTP_PROXY environment variable??

```
export HTTP_PROXY="http://proxyIp:proxyPort"
```

If you test it - let me know. I will try it when I have time. I suspect it may just work.

**Comment by qiaolei81** [comment]
@pr8kerl thanks for the reply
I already tested with HTTP_PROXY&HTTPS_PROXY environment variable which does not work.

I found the code snippet in f5.go, and should pass the http.ProxyFromEnvironment when constructing the http.Transport

```
func (f *Device) InitSession() {

	// REST connection setup
	if f.Proto == "https" {
		tsport = http.Transport{
			TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
			Proxy: http.ProxyFromEnvironment,
		}
		clnt = http.Client{Transport: &tsport}
	} else {
		clnt = http.Client{}
	}
	headers = make(http.Header)

	//
	// Setup HTTP Basic auth for this session (ONLY use this with SSL).  Auth
	// can also be configured on a per-request basis when using Send().
	//
	f.Session = napping.Session{
		Client: &clnt,
		Log:    debug,
		// if Userinfo is set - napping will set the basic auth header for you
		Userinfo: url.UserPassword(f.Username, f.Password),
		Header:   &headers,
	}

}
```

**Comment by pr8kerl** [comment]
@qiaolei81 apologies - have been away.

Thanks for the pointer. Added now. Works ok for me. Let me know if issues.

Tx
